baseURL = "http://lagerskola2020.lokala.org"
languageCode = "sv"
title = "Finno skola lägerskola"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "sv-SV"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "yearly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Lägerskola 2020"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/img/finno.jpg"
  recent_posts_number = 5
